routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware("web")->name("admin.")->group(function () {
    Route::namespace("Administrator")->group(function () {
        Route::get("dashboard", "DashboardController@index")->name("dashboard");

        /**
         * Teacher route resource
         */
        Route::resource("teacher", "TeacherController");

        /**
         * Class route resource
         */
        Route::resource("classes", "ClassesController");

        /**
         * Class route resource
         */
        Route::resource("materi", "MaterialController");

        /**
         * assignment
         */
        Route::resource("soal", "AssignmentController");


        /**
         * STudent route
         */
        Route::resource("student", "StudentController");

        Route::get("materi", "MaterialController@index")->name("materi.index");

        Route::get("test", "TestController@index")->name("test.index");

//        Route::get("soal", "SoalController@index")->name("soal.index");

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::middleware("home.authenticate")->group(function () {
    Route::get('/', function () {
        return view('welcome');
    });
});

Route::group([
    "middleware" => ["web"]
], function () {
    /**
     * Dashboard
     */
    Route::get("/dashboard", "Student\DashboardController@index")->name("dashboard");
    Route::get("/dashboard", "Teacher\DashboardController@index")->name("dashboard");
    Route::get("/dashboard", "Administrator\DashboardController@index")->name("dashboard");

    /**
     * Login
     */
    Route::get("/login", "Auth\LoginController@index")->name("login.index");
    Route::post("/login", "Auth\LoginController@login")->name("login.login");
});

Route::post("/logout", "Auth\LogoutController@index")->name("logout.index");

app/Http/Controllers/Administrator/TeacherController.php
<?php

namespace App\Http\Controllers\Administrator;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\StoreUser;
use EPro\Teacher\TeacherRepository;
use EPro\User\Application\CreateUser;
use Illuminate\Http\Request;

class TeacherController extends Controller
{

    protected $teacherRepositoy;

    public function __construct()
    {
        $this->teacherRepositoy = new TeacherRepository();
    }

    public function index(Request $request)
    {
        try {
            $result = $this->teacherRepositoy->list($request->session()->get("token"));
            return view("admin.teacher.list-teacher", [
                "teachers" => $result->data
            ]);
        } catch (\Exception $exception) {
            return redirect()->back();
        }
    }

    public function show($id)
    {
        try {
            $result = $this->teacherRepositoy->detail($id);
            dd($result);
        } catch (\Exception $exception) {
            dd($exception);
        }
    }

    public function create()
    {
        try {
            return view("admin.teacher.add-teacher");
        } catch (\Exception $exception) {
            dd($exception);
        }
    }

    public function store(StoreUser $request)
    {
        try {
            $createUser = new CreateUser();
            $request["role"] = "TEACHER";
            $createUser->store($request->except("_token"), $request->session()->get("token"));
            flash("Sucessfully add new teacher!")->important()->success();
            return redirect()->route("admin.teacher.index");
        } catch (\Exception $exception) {
            flash($exception->getMessage())->error()->important();
            return redirect()->back();
        }
    }

    public function edit($id)
    {
        try {

        } catch (\Exception $exception) {
            dd($exception);
        }
    }

    public function update($id, Request $request)
    {
        try {

        } catch (\Exception $exception) {
            dd($exception);
        }
    }
}

resources/views/admin/teacher/add-teacher.blade.php
@extends('layout.app')

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body">
			<div class="bg-light lter b-b wrapper-md">
				<div class="row">
					<div class="col-md-4 col-sm-12 col-xs-12" style="padding-bottom:5px;">
						<h1 class="m-n font-thin h3">Add teacher</h1>
						<i class="text-muted text-sm">Here you can add new teacher data</i>
					</div>
				</div>
			</div>

			<div class="wrapper-md" id="addbooks">
				<div class="row">
					<div class="col-md-3" style="padding: 16px">
						<h3>Add Teacher</h3>
			            <br>
			            <p style="text-align: justify">
			                <strong>Instruction</strong> : <br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
			            </p>
					</div>
					<div class="col-md-9">
						@include('flash::message')
						<div class="card">
							<div class="body">
                    			<div class="card-inner">
                        			<h4 class="card-inner-header">Data Pengajar</h4>

                        			<form method="POST" action="{{ route("admin.teacher.store") }}">

		                                {{ csrf_field() }}

		                                <div class="form-group">
		                                    <label for="class_name" class="config-label">Name :</label>
		                                    <input id="class_name" type="text" class="form-control" name="name" required/>
		                                </div>
		                                <div class="form-group">
		                                    <label for="class_name" class="config-label">Email :</label>
		                                    <input id="class_name" type="email" class="form-control" name="email" required/>
		                                </div>
		                                <div class="form-group">
		                                    <label for="class_name" class="config-label">Phone Number :</label>
		                                    <input id="class_name" type="text" class="form-control" name="phone" required/>
		                                </div>
		                                <div class="form-group">
		                                    <label for="class_name" class="config-label">Username :</label>
		                                    <input id="class_name" type="text" class="form-control" name="username" required/>
		                                </div>
		                                <div class="row">
		                                    <div class="col-md-6">
		                                        <div class="form-group">
		                                            <label for="class_name" class="config-label">Password :</label>
		                                            <input id="class_name" type="password" class="form-control" name="password" required/>
		                                        </div>
		                                    </div>
		                                    <div class="col-md-6">
		                                        <div class="form-group">
		                                            <label for="class_name" class="config-label">Password Confirmation :</label>
		                                            <input id="class_name" type="password" class="form-control" name="password_confirmation" required/>
		                                        </div>
		                                    </div>
		                                </div>
		                                <button class="btn btn-danger waves-effect" type="reset"><em class="fa fa-times"></em>
		                                    Cancel
		                                </button>
		                                <button class="btn btn-primary waves-effect" type="submit"><em class="fa fa-check"></em>
		                                    Submit
		                                </button>
		                            </form>
                        		</div>
                        	</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

@push('scripts')
	<script type="text/javascript">
		$("input[type=text]").attr("autocomplete", "off");
	</script>
@endpush

resources/views/admin/teacher/list-teacher.blade.php
@extends('layout.app')

@push('title')
	<title>E-Pro | List Teacher</title>
@endpush

@push('styles')
	<style type="text/css">
		.table > tbody > tr > td {
            vertical-align: middle;
        }

        .table > thead > tr > th {
            font-weight: bold;
        }

        .table > tbody > tr > td:nth-child(1) {
            font-weight: bold;
        }
	</style>
@endpush

@section('content')
	<div id="content" class="app-content" role="main">
		<div class="app-content-body">
			<div class="bg-light lter b-b wrapper-md">
				<div class="row">
					<div class="col-md-4 col-sm-12 col-xs-12" style="padding-bottom:5px;">
						<h1 class="m-n font-thin h3">List teacher</h1>
						<i class="text-muted text-sm">Here you can manage teachers data</i>
					</div>
					<div class="col-md-4 col-sm-6 col-xs-6">
						<div class="text-primary-dk font-thin h3"><span id="txTotalProduk">{{ count($teachers) }}</span></div>
          				<i class="text-muted text-sm">Teacher Total</i>
					</div>
					<div class="col-md-4 col-sm-6 col-xs-4" align="right">
						<a href="{{ route('admin.teacher.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add Teacher</a>
					</div>
				</div>
			</div>

			<div class="wrapper-md" id="addbooks" style="background-color: white;">
				@include('flash::message')
				<div class="panel panel-default" style="padding: 10px; margin:-17px; border:0px; box-shadow:none;">
					<div class="panel-body b-b b-light">
				      	Teacher Look up: <input id="filter" type="text" class="form-control input-sm w-sm inline m-r"/>
				    </div>
				    <div>
				    	<table class="table m-b-none" ui-jq="footable" data-filter="#filter" id="tabelBooks" data-page-size="10">
							<thead class="bg-primary">
								<tr>
									<th>#</th>
									<th>NAME</th>
									<th data-hide="phone,tablet" data-name="E-mail">E-MAIL</th>
									<th data-hide="phone,tablet" data-name="Phone">PHONE NUMBER</th>
									<th data-hide="phone" data-name="Manage">MANAGE</th>
								</tr>
							</thead>
							<tbody>
								@forelse ($teachers as $teacher)
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{ $teacher->name }}</td>
										<td><a href="mailto:{{ $teacher->email }}">{{ $teacher->email }}</a></td>
										<td>{{ $teacher->phone }}</td>
										<td>
											<button type="button" class="btn btn-xs btn-primary" style="font-weight: bold;" disabled><em class="fa fa-eye"></em> Detail</button>
											<button type="button" class="btn btn-xs btn-warning" style="font-weight: bold;" disabled><em class="fa fa-pencil-square-o"></em> Edit</button>
											<button type="button" class="btn btn-xs btn-danger" style="font-weight: bold;" disabled><em class="fa fa-pencil-square-o"></em> Delete</button>
										</td>
									</tr>
								@empty
									<tr>
										<td colspan="4">Teacher data is empty</td>
									</tr>
								@endforelse
							</tbody>
							<tfoot>
					        	<tr>
					            	<td colspan="5" class="text-center">
					                	<ul class="pagination"></ul>
					              	</td>
					          	</tr>
					        </tfoot>
				    	</table>
				    </div>
				</div>
			</div>
		</div>
	</div>

	<div class="modal fade" id="imgPreview">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-body">
					<center><img id="theImg" alt="" width="100%" style="max-height:350px;"></center>
				</div>
				<div class="modal-footer">
					<center><button class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i> Tutup</button></center>
				</div>
			</div>
		</div>
	</div>
@endsection