routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware("web")->name("admin.")->group(function () {
    Route::namespace("Administrator")->group(function () {
        Route::get("dashboard", "DashboardController@index")->name("dashboard");

        /**
         * Teacher route resource
         */
        Route::resource("teacher", "TeacherController");

        /**
         * Class route resource
         */
        Route::resource("classes", "ClassesController");

        /**
         * Class route resource
         */
        Route::resource("materi", "MaterialController");

        /**
         * assignment
         */
        Route::resource("soal", "AssignmentController");


        /**
         * STudent route
         */
        Route::resource("student", "StudentController");

        Route::get("materi", "MaterialController@index")->name("materi.index");

        Route::get("test", "TestController@index")->name("test.index");

//        Route::get("soal", "SoalController@index")->name("soal.index");

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::middleware("home.authenticate")->group(function () {
    Route::get('/', function () {
        return view('welcome');
    });
});

Route::group([
    "middleware" => ["web"]
], function () {
    /**
     * Dashboard
     */
    Route::get("/dashboard", "Student\DashboardController@index")->name("dashboard");
    Route::get("/dashboard", "Teacher\DashboardController@index")->name("dashboard");
    Route::get("/dashboard", "Administrator\DashboardController@index")->name("dashboard");

    /**
     * Login
     */
    Route::get("/login", "Auth\LoginController@index")->name("login.index");
    Route::post("/login", "Auth\LoginController@login")->name("login.login");
});

Route::post("/logout", "Auth\LogoutController@index")->name("logout.index");

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
	@stack('title')
	<link rel="stylesheet" href="{{ asset('plugins/bootstrap/css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/app.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/font-awesome/css/font-awesome.min.css') }}">
	<link rel="stylesheet" href="{{ asset('css/custom.css') }}">
	@stack('styles')
</head>
<body>
	<div class="app app-header-fixed">
		<header id="header" class="app-header navbar" role="menu">
			<div class="navbar-header bg-dark">
				<button class="pull-right visible-xs dk" ui-toggle="show" target=".navbar-collapse"><i class="glyphicon glyphicon-cog"></i></button>
				<button class="pull-right visible-xs" ui-toggle="off-screen" target=".app-aside" ui-scroll="app"><i class="glyphicon glyphicon-align-justify"></i></button>
				<a href="" class="navbar-brand text-lt">
			        <i class="fa fa-book" aria-hidden="true"></i>
			        <span class="hidden-folded m-l-xs">E-PRO</span>
			    </a>
			</div>
			<div class="collapse pos-rlt navbar-collapse box-shadow bg-white-only">
				<div class="nav navbar-nav hidden-xs">
					<a href="" class="btn no-shadow navbar-btn" ui-toggle="app-aside-folded" target=".app">
			            <i class="fa fa-dedent fa-fw text"></i>
			            <i class="fa fa-indent fa-fw text-active"></i>
			        </a>
			        <a href="" class="btn no-shadow navbar-btn" ui-toggle="show" target="#aside-user">
			            <i class="icon-user fa-fw"></i>
			        </a>
				</div>
				<ul class="nav navbar-nav navbar-right">
          			<li class="dropdown">
			            <a href="" data-toggle="dropdown" class="dropdown-toggle clear" data-toggle="dropdown">
			              	<span class="thumb-sm avatar pull-right m-t-n-sm m-b-n-sm m-l-sm">
			                	<img src="{{ asset('img/a0.jpg') }}" alt="...">
			                	<i class="on md b-white bottom"></i>
			              	</span>
			              	<span class="hidden-sm hidden-md">{{ session()->get('name') }}</span> <b class="caret"></b>
			            </a>
			            <ul class="dropdown-menu animated fadeInRight w">
			              	<li>
			                	<a data-toggle="modal" data-target="#modalLogout"><i class="fa fa-sign-out"></i> Log out</a>
			              	</li>
			            </ul>
          			</li>
        		</ul>
			</div>
		</header>

		@if (session()->get('role') === 'ADMIN')
			@include('layout.sidebar-admin')
		@elseif (session()->get('role') === 'STUDENT')
			@include('layout.sidebar-admin')
		@elseif (session()->get('role') === 'TEACHER')
			@include('layout.sidebar-admin')
		@endif

  		@yield('content')
	</div>

	<div class="modal fade" id="modalLogout">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-body" align="center">
					<strong>Are you sure want to log out?</strong>
				</div>
				<div class="modal-footer">
					<center>
						<form action="{{ route('logout.index') }}" method="POST">
							{!! csrf_field() !!}
							<button class="btn btn-default" data-dismiss="modal"><i class="fa fa-close"></i> No</button>
							<button class="btn btn-danger" type="submit" name="confirmed"><i class="fa fa-sign-out"></i> Yes</button>
						</form>
					</center>
				</div>
			</div>
		</div>
	</div>

	<script src="{{ asset('plugins/jQuery/jquery.min.js') }}"></script>
	<script src="{{ asset('plugins/bootstrap/js/bootstrap.js') }}"></script>
	<script src="{{ asset('js/ui-load.js') }}"></script>
	<script src="{{ asset('js/ui-jp.config.js') }}"></script>
	<script src="{{ asset('js/ui-jp.js') }}"></script>
	<script src="{{ asset('js/ui-nav.js') }}"></script>
	<script src="{{ asset('js/ui-toggle.js') }}"></script>
	@stack("scripts")
</body>
</html>

resources/views/layout/sidebar-admin.blade.php
<aside id="aside" class="app-aside hidden-xs bg-dark">
	<br>
  	<div class="aside-wrap">
  		<nav ui-nav class="navi clearfix">
			<ul class="nav">
				<li><a href="" class="auto"><i class="fa fa-dashboard icon text-primary"></i><span class="font-bold">Dashboard</span></a></li>
				<li>
					<a href class="auto">
						<span class="pull-right text-muted">
							<i class="fa fa-fw fa-angle-right text"></i>
							<i class="fa fa-fw fa-angle-down text-active"></i>
						</span>
						<i class="fa fa-book text-success"></i>
						<span>Teacher</span>
					</a>
					<ul class="nav nav-sub dk">
						<li class="nav-sub-header"><a href><span>Teacher</span></a></li>
						<li><a href=""><span>Add Teacher</span></a></li>
						<li><a href="{{ route('admin.teacher.index') }}"><span>List Teacher</span></a></li>
					</ul>
				</li>
				{{-- <li>
					<a href class="auto">
						<span class="pull-right text-muted">
							<i class="fa fa-fw fa-angle-right text"></i>
							<i class="fa fa-fw fa-angle-down text-active"></i>
						</span>
						<i class="fa fa-users text-warning"></i>
						<span>Anggota</span>
					</a>
					<ul class="nav nav-sub dk">
						<li class="nav-sub-header"><a href><span>Anggota</span></a></li>
						<li><a href=""><span>Tambah Anggota</span></a></li>
						<li><a href=""><span>Daftar Anggota</span></a></li>
					</ul>
				</li>
				<li>
					<a href class="auto">
						<span class="pull-right text-muted">
							<i class="fa fa-fw fa-angle-right text"></i>
							<i class="fa fa-fw fa-angle-down text-active"></i>
						</span>
						<i class="fa fa-exchange text-danger"></i>
						<span>Pinjaman</span>
					</a>
					<ul class="nav nav-sub dk">
						<li class="nav-sub-header"><a href><span>Pinjaman</span></a></li>
						<li><a href=""><span>Tambah Pinjaman</span></a></li>
						<li><a href=""><span>Daftar Pinjaman</span></a></li>
					</ul>
				</li>
				<li><a href="" class="auto"><i class="glyphicon glyphicon-stats icon tet-primary-dker"></i><span>Laporan</span></a></li>
				<li><a href="" class="auto"><i class="fa fa-question-circle"></i><span>Bantuan</span></a></li> --}}
			</ul>
  		</nav>
	</div>
</aside>